run-dist:
	./build/install/app/bin/app src/main/resources/file3.json src/main/resources/file4.json
start:
	./gradlew run
build:
	./gradlew build
clean:
	./gradlew clean
test:
	./gradlew test
report:
	./gradlew jacocoTestReport
lint:
	./gradlew checkstyleMain checkstyleTest
build-run:
	build run
.PHONY: build
