name: Java CIon:
  - push
  - pull_requestjobs:
  build:
    runs-on: ubuntu-lateststeps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3with:
          java-version: '21'distribution: 'temurin'
      - uses: gradle/gradle-build-action@v2with:
          gradle-version: 8.5arguments: buildbuild-root-directory: app
      - name: Publish code coverageuses: paambaati/codeclimate-action@v5.0.0env:
          CC_TEST_REPORTER_ID: ${{secrets.CC_TEST_REPORTER_ID}}JACOCO_SOURCE_PATH: app/src/main/javawith:
          coverageCommand: make reportcoverageLocations: ${{github.workspace}}/app/build/reports/jacoco/test/jacocoTestReport.xml:jacoco
